### ISSUE TITLE
Icons are spaced very tightly

### ISSUE THREAD

**Issue by FiniTea** [glutanimate/sticky-searches#1]
Hi

As you see in the picture, there is very little space between the icons. Is there a way to make the search bar smaller or fi that another way?

Using MacOS Sierra 10.12.6 and Anki 2.0.41
![bildschirmfoto 2017-08-11 um 20 42 57](https://user-images.githubusercontent.com/30936634/29227346-c77f37b2-7ed5-11e7-8954-4efd9cbd7e96.png)

**Comment by glutanimate** [comment]
Thanks for the report! Looks like this is a macOS-specific issue. I have implemented a possible fix that adjusts the margins of the icons. Could you please give the latest master branch a try and see if things have improved? (I don't have a Mac to test this)

You can grab the latest master branch zip [here](https://github.com/glutanimate/sticky-searches/archive/master.zip). Then just follow the [manual installation instructions](https://github.com/glutanimate/sticky-searches#installation) while using the master.zip at step 3 instead of the latest release zip.

Thanks in advance!

**Comment by FiniTea** [comment]
nice one sir! It worked! Thanks!

**Comment by glutanimate** [comment]
Great, thanks for giving it a try!
